# Generated by Django 3.0.2 on 2021-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_auto_20210315_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
