# Generated by Django 3.0.2 on 2020-02-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porgrammer',
            new_name='Programmer',
        ),
    ]
