# Generated by Django 3.0.2 on 2020-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0002_auto_20200207_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='programmers.Language'),
        ),
    ]
